# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: iron
  template:
    metadata:
      labels:
        app: iron
    spec:
      containers:
        - name: iron
          image: iron/images # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listens on
